FROM continuumio/miniconda3:23.9.0-0
LABEL maintainer="Camilo Laiton <camilo.laiton@alleninstitute.org>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN conda create -n flatfield_estimation python=3.9 --no-default-packages -y && \
    conda clean --all --yes

ENV PATH="/opt/conda/envs/flatfield_estimation/bin:$PATH"

RUN conda run -n flatfield_estimation pip install --no-cache-dir \
    aind-data-schema==1.0.0 \
    "dask[distributed]" \
    numpy==1.24.2 \
    BaSiCPy==1.1.0 \
    jax==0.4.23 \
    jaxlib==0.4.23 \
    zarr==2.18.2 \
    matplotlib \
    natsort==8.4.0 \
    PyWavelets==1.6.0
